{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "5b0dcc8b_e908ea4d",
        "filename": "occ_status.cpp",
        "patchSetId": 3
      },
      "lineNbr": 217,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2022-04-05T13:36:11Z",
      "side": 1,
      "message": "is that OK if it still continues on to the sendIpsData after deviceError runs?",
      "revId": "2e3f49089881160e6df27e358aff1a39e2138421",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}